###############################################################################
#
#  hindex Unit Testing Module Makefile
#
#  
#
###############################################################################
MODULE := hindex_utest
NOMODULEMAKE := 1
TEST_MODULE :=  hindex
PEDANTIC := 1
DEPENDMODULES := AIM
include ../make/utestmodule.mk
