################################################################
#
#        Copyright 2013, Big Switch Networks, Inc. 
# 
# Licensed under the Eclipse Public License, Version 1.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
# 
#        http://www.eclipse.org/legal/epl-v10.html
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied. See the License for the specific
# language governing permissions and limitations under the
# License.
#
################################################################


##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-05-22 14:36:57.056667
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
AIM_BASEDIR := $(BASEDIR)AIM
BigHash_BASEDIR := $(BASEDIR)BigData/BigHash
BigList_BASEDIR := $(BASEDIR)BigData/BigList
BigRing_BASEDIR := $(BASEDIR)BigData/BigRing
list_BASEDIR := $(BASEDIR)BigData/list
nwac_BASEDIR := $(BASEDIR)BigData/nwac
ELS_BASEDIR := $(BASEDIR)ELS
FME_BASEDIR := $(BASEDIR)FME
Faultd_BASEDIR := $(BASEDIR)Faultd
IOF_BASEDIR := $(BASEDIR)IOF
IVS_BASEDIR := $(BASEDIR)IVS
AET_BASEDIR := $(BASEDIR)Indigo/AET
Configuration_BASEDIR := $(BASEDIR)Indigo/Configuration
Forwarding_BASEDIR := $(BASEDIR)Indigo/Forwarding
OFConnectionManager_BASEDIR := $(BASEDIR)Indigo/OFConnectionManager
OFStateManager_BASEDIR := $(BASEDIR)Indigo/OFStateManager
PortManager_BASEDIR := $(BASEDIR)Indigo/PortManager
SocketManager_BASEDIR := $(BASEDIR)Indigo/SocketManager
indigo_BASEDIR := $(BASEDIR)Indigo/indigo
LoxiGen_BASEDIR := $(BASEDIR)LoxiGen
NPP_BASEDIR := $(BASEDIR)NPP
NSS_BASEDIR := $(BASEDIR)NSS
OS_BASEDIR := $(BASEDIR)OS
PPE_BASEDIR := $(BASEDIR)PPE
VASIC_BASEDIR := $(BASEDIR)VASIC
VPI_BASEDIR := $(BASEDIR)VPI
cjson_BASEDIR := $(BASEDIR)cjson
loci_BASEDIR := $(BASEDIR)loci
locitest_BASEDIR := $(BASEDIR)locitest
murmur_BASEDIR := $(BASEDIR)murmur
snmp_BASEDIR := $(BASEDIR)snmp
uCli_BASEDIR := $(BASEDIR)uCli
sofc_BASEDIR := $(BASEDIR)sofc
pimu_BASEDIR := $(BASEDIR)pimu


ALL_MODULES := $(ALL_MODULES) BigHash pimu indigo AET Faultd loci OFStateManager OFConnectionManager AIM locitest BigList Forwarding uCli BigRing SocketManager PPE snmp IOF NSS VPI VASIC murmur ELS FME nwac Configuration cjson sofc list PortManager IVS LoxiGen OS NPP
