
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2015-04-22 22:33:20.309985
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
Configuration_BASEDIR := $(BASEDIR)Configuration
OFConnectionManager_BASEDIR := $(BASEDIR)OFConnectionManager
OFConnectionManager2_BASEDIR := $(BASEDIR)OFConnectionManager2
OFStateManager_BASEDIR := $(BASEDIR)OFStateManager
SocketManager_BASEDIR := $(BASEDIR)SocketManager
indigo_BASEDIR := $(BASEDIR)indigo
loci_BASEDIR := $(BASEDIR)loci
minimatch_BASEDIR := $(BASEDIR)minimatch


ALL_MODULES := $(ALL_MODULES) Configuration OFConnectionManager OFConnectionManager2 OFStateManager SocketManager indigo loci minimatch
