
##############################################################################
#
# Module Directory Location Variable Manifest.
#
# Autogenerated 2013-10-18 14:28:57.395934
#
##############################################################################
CONFIGURATION=`dirname $BASH_SOURCE`/Configuration/module
OFCONNECTIONMANAGER=`dirname $BASH_SOURCE`/OFConnectionManager/module
OFSTATEMANAGER=`dirname $BASH_SOURCE`/OFStateManager/module
SOCKETMANAGER=`dirname $BASH_SOURCE`/SocketManager/module
INDIGO=`dirname $BASH_SOURCE`/indigo/module
LOCI=`dirname $BASH_SOURCE`/loci/module
LOCITEST=`dirname $BASH_SOURCE`/locitest/module

