
##############################################################################
#
# Module Directory Location Variable Manifest.
#
# Autogenerated 2013-06-11 15:28:50.679997
#
##############################################################################
AIM=`dirname $BASH_SOURCE`/AIM/module
BIGLIST=`dirname $BASH_SOURCE`/BigData/BigList/module
CONFIGURATION=`dirname $BASH_SOURCE`/Indigo/Configuration/module
OFCONNECTIONMANAGER=`dirname $BASH_SOURCE`/Indigo/OFConnectionManager/module
OFSTATEMANAGER=`dirname $BASH_SOURCE`/Indigo/OFStateManager/module
SOCKETMANAGER=`dirname $BASH_SOURCE`/Indigo/SocketManager/module
INDIGO=`dirname $BASH_SOURCE`/Indigo/indigo/module
CJSON=`dirname $BASH_SOURCE`/cjson/module
LOCI=`dirname $BASH_SOURCE`/loci/module
LOCITEST=`dirname $BASH_SOURCE`/locitest/module
MURMUR=`dirname $BASH_SOURCE`/murmur/module

