
##############################################################################
#
# Module Directory Location Variable Manifest.
#
# Autogenerated 2013-05-30 16:20:13.217420
#
##############################################################################
MURMUR=/code/bigcode/indigo/Modules/murmur/module
LOCI=/code/bigcode/indigo/Modules/loci/module
OFSTATEMANAGER=/code/bigcode/indigo/Modules/Indigo/OFStateManager/module
CONFIGURATION=/code/bigcode/indigo/Modules/Indigo/Configuration/module
SOCKETMANAGER=/code/bigcode/indigo/Modules/Indigo/SocketManager/module
OFCONNECTIONMANAGER=/code/bigcode/indigo/Modules/Indigo/OFConnectionManager/module
INDIGO=/code/bigcode/indigo/Modules/Indigo/indigo/module
CJSON=/code/bigcode/indigo/Modules/cjson/module
LOCITEST=/code/bigcode/indigo/Modules/locitest/module
BIGLIST=/code/bigcode/indigo/Modules/BigData/BigList/module
AIM=/code/bigcode/indigo/Modules/AIM/module

