
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-06-11 15:30:13.480198
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
AIM_BASEDIR := $(BASEDIR)AIM
BigList_BASEDIR := $(BASEDIR)BigData/BigList
Configuration_BASEDIR := $(BASEDIR)Indigo/Configuration
OFConnectionManager_BASEDIR := $(BASEDIR)Indigo/OFConnectionManager
OFStateManager_BASEDIR := $(BASEDIR)Indigo/OFStateManager
SocketManager_BASEDIR := $(BASEDIR)Indigo/SocketManager
indigo_BASEDIR := $(BASEDIR)Indigo/indigo
cjson_BASEDIR := $(BASEDIR)cjson
loci_BASEDIR := $(BASEDIR)loci
locitest_BASEDIR := $(BASEDIR)locitest
murmur_BASEDIR := $(BASEDIR)murmur


ALL_MODULES := $(ALL_MODULES) indigo SocketManager cjson loci OFStateManager OFConnectionManager AIM murmur locitest BigList Configuration
