
##############################################################################
#
# Builder Module Manifest.
#
# Autogenerated 2013-10-18 14:28:57.392938
#
##############################################################################
BASEDIR := $(dir $(lastword $(MAKEFILE_LIST)))
Configuration_BASEDIR := $(BASEDIR)Configuration
OFConnectionManager_BASEDIR := $(BASEDIR)OFConnectionManager
OFStateManager_BASEDIR := $(BASEDIR)OFStateManager
SocketManager_BASEDIR := $(BASEDIR)SocketManager
indigo_BASEDIR := $(BASEDIR)indigo
loci_BASEDIR := $(BASEDIR)loci
locitest_BASEDIR := $(BASEDIR)locitest


ALL_MODULES := $(ALL_MODULES) Configuration OFConnectionManager OFStateManager SocketManager indigo loci locitest
