###############################################################################
#
#  Makefile
#
#  hindex Makefile
#
###############################################################################
MODULE :=  hindex
AUTOMODULE :=  hindex

ifndef BUILDER
$(error Please set the $$BUILDER variable)
endif

include $(BUILDER)/definemodule.mk
